services:
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbixagent
    ports:
      - 10050:10050
    environment:
      - ZBX_HOSTNAME=db
      - ZBX_SERVER_HOST=192.168.0.15
    privileged: true
    restart: always