services:
  zabbix:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix
    ports:
      - 10080:80
      - 10051:10051
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=saoindrg:kjaprhrf
      - DB_SERVER_PORT=3306
      - DB_SERVER_HOST=192.168.0.15
    restart: always
networks:
  defaults:
    external:
      name: bridge