services:
  zabbixserver:
    image: zabbix/zabbix-server-mysql
    container_name: zabbixserver
    ports:
      - 10051:10051
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=saoindrg:kjaprhrf
      - DB_SERVER_PORT=3306
      - DB_SERVER_HOST=192.168.0.15
    restart: always
  zabbixweb:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbixweb
    ports:
      - 9001:9000
    restart: always
    environment:
      - ZBX_SERVER_HOST=192.168.0.15
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=192.168.0.15
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=saoindrg:kjaprhrf
networks:
  defaults:
    external:
      name: bridge